name: Build and Deploy

on:
  # push:
  #   branches:
  #     - '**'       # Existing push trigger for main branch
  pull_request:
    branches:
      - '**'       # Existing PR trigger for main branch
  # workflow_dispatch:         # Manual trigger available on any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker images for your applications
      - name: Build blackdragonai-api image
        run: |
          docker build -t blackdragonai-web -f ./BlackDragonAI_Manager/Dockerfile ./BlackDragonAI_Manager

      # Save the built Docker images as tarballs
      - name: Save Docker images to tar files
        run: |
          docker save blackdragonai-web -o blackdragonai-web.tar
          ls

      - name: Copy files to NAS
        run: |
          echo '${{ secrets.FEYENAS_SSH_PASSWORD }}' | sudo -S apt-get install -y sshpass
          ls
          sshpass -p '${{ secrets.FEYENAS_SSH_PASSWORD }}' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P ${{ secrets.FEYENAS_SSH_PORT }} blackdragonai-web.tar ${{ secrets.FEYENAS_SSH_USERNAME }}@${{ secrets.FEYENAS_SSH_HOST }}:${{ secrets.FEYENAS_HOME_PATH }}/blackdragonai/deploy

      # Load images on the server and deploy using Docker Compose
      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.FEYENAS_SSH_HOST }}
          username: ${{ secrets.FEYENAS_SSH_USERNAME }}
          port: ${{ secrets.FEYENAS_SSH_PORT }}
          password: ${{ secrets.FEYENAS_SSH_PASSWORD }}
          script: |
            cd ${{ secrets.FEYENAS_HOME_PATH }}/blackdragonai/deploy

            echo "${{ secrets.FEYENAS_SSH_PASSWORD }}" | sudo -S docker load -i blackdragonai-web.tar
            echo "${{ secrets.FEYENAS_SSH_PASSWORD }}" | sudo -S docker compose down
            echo "${{ secrets.FEYENAS_SSH_PASSWORD }}" | sudo -S docker compose up -d
